[package]
name = "kademlia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluesea-identity = { workspace = true }
arrayvec = "0.7.2"
rand = "0.8"
smallvec = "1.6.1"

[dev-dependencies]
quickcheck = { workspace = true }