#!/bin/bash

HAS_ISSUES=0
FIRST_FILE=1

for file in $(git diff --name-only --staged); do
    FMT_RESULT="$(rustfmt --check $file 2>/dev/null || true)"
    if [ "$FMT_RESULT" != "" ]; then
        echo "$file"
        HAS_ISSUES=1
        FIRST_FILE=0
    fi
done

if [ $HAS_ISSUES -eq 0 ]; then
    exit 0
fi

echo "Your code has formatting issues in files listed above. Format your code with \`make format\` or call rustfmt manually."
exit 1
