[package]
name = "atm0s-sdn-virtual-socket"
version = "0.1.1"
edition = "2021"
description = "Virtual Socket service in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-identity = { path = "../../core/identity", version = "0.2.0" }
atm0s-sdn-router = { path = "../../core/router", version = "0.1.4" }
atm0s-sdn-utils = { path = "../../core/utils", version = "0.1.1" }
atm0s-sdn-network = { path = "../../network", version = "0.3.1" }
log = { workspace = true }
futures = "0.3"
async-trait = { workspace = true }
async-std = { workspace = true }
parking_lot = { workspace = true }
quinn = { version = "0.10.2", default-features = false, features = ["runtime-async-std", "log", "futures-io"], optional = true }
quinn-plaintext = "0.2.0"

[features]
default = ["quic"]
quic = ["quinn"]
