[package]
name = "key-value-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { workspace = true }

[dev-dependencies]
dhat = { workspace = true }
utils = { workspace = true, features = ["auto-clear"] }