[package]
authors = ["dignifiedquire <dignifiedquire@gmail.com>", "Parity Technologies <admin@parity.io>"]
description = "Implementation of the multiaddr format"
edition = "2021"
rust-version = "1.59.0"
homepage = "https://github.com/multiformats/rust-multiaddr"
keywords = ["multiaddr", "ipfs"]
license = "MIT"
name = "atm0s-sdn-multiaddr"
readme = "README.md"
version = "0.1.1"


[features]
default = ["url"]

[dependencies]
arrayref = "0.3"
byteorder = "1.5.0"
data-encoding = "2.5"
multibase = "0.9.1"
percent-encoding = "2.3.1"
serde = "1.0.193"
static_assertions = "1.1"
unsigned-varint = "0.8"
url = { version = "2.5.0", optional = true, default-features = false }

[dev-dependencies]
bincode = "1"
quickcheck = { version = "1.0.3", default-features = false }
rand = "0.8.5"
serde_json = "1.0"
